%YAML:1.0
---
# 使用单帧图像("Image")，视频流("Video")还是多张图像("MultiView")
InputFormat: "MultiView"
# 输入存放多张图像的文件夹路径(使用多图像时才有效，且注意图片以1，2，3，...的方式命名)
ImagesDir: "/home/jc/userData/2_Project/cpp_code/vision_measure/resources/images"
ImageFormat: ".jpg"
ImageNums: 2
# 输入图像路径(使用单帧图像时才有效)
ImagePath: "/home/jc/userData/2_Project/cpp_code/vision_measure/resources/test1.jpg"
# 使用的摄像头类型(使用视频流时才有效)，有两个选项：填入"Web_Cam"表示使用外置摄像头，填入"Internal_Cam"表示使用笔记本自带摄像头
Camera: "Web_Cam"
# 编码的位数
Bit_N: 12
# 椭圆圆度评估阈值（0～1）
R_threshold: 0.85